import {parseState,serializeState,palettes} from './layout.js';
let state=parseState(location.hash),model;
const $=s=>document.querySelector(s);
const concepts={
 original:{tag:'ИСХОДНАЯ СХЕМА',title:'Отправная точка',description:'Три отдельные комнаты и кухня 16,91 м². Сравните исходную оболочку с двумя вариантами объединения.',area:'16,91 м²',caption:'отдельная кухня по плану',note:'Исходная схема. Мебель добавлена условно для масштаба.'},
 table:{tag:'ВАРИАНТ 01',title:'Собираться вместе',description:'Объединяем кухню с соседней комнатой. Большой стол у окна, диван в отдельной зоне и кухня на привычном месте.',area:'28,16 м²',caption:'16,91 + 11,25 м² по плану',note:'Условно убираем перегородку между кухней и соседней комнатой.'},
 peninsula:{tag:'ВАРИАНТ 02',title:'Готовить с удовольствием',description:'Та же большая кухня-гостиная, но с полуостровом без мойки и плиты. Дополнительная столешница и компактная обеденная группа.',area:'28,16 м²',caption:'та же оболочка, другая мебель',note:'Полуостров без переноса воды. Проходы уточним после обмеров.'}
};
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3600);}
function updateUI(){for(const key of ['variant','palette','view'])document.querySelectorAll(`[data-${key}]`).forEach(el=>{const active=el.dataset[key]===state[key];el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});const c=concepts[state.variant];for(const [id,key] of [['variant-tag','tag'],['variant-title','title'],['variant-description','description'],['kitchen-area','area'],['area-caption','caption'],['model-note','note']])$('#'+id).textContent=c[key];$('#palette-name').textContent=palettes[state.palette].name;$('#furniture').checked=state.furniture;$('#full-walls').checked=state.walls==='full';history.replaceState(null,'',serializeState(state));}
function setState(patch){const prev=state;state={...state,...patch};updateUI();if(model){if(prev.variant!==state.variant||prev.palette!==state.palette||prev.walls!==state.walls||prev.furniture!==state.furniture)model.rebuild(state);if(prev.view!==state.view)model.setView(state.view);}}
for(const key of ['variant','palette','view'])document.querySelectorAll(`[data-${key}]`).forEach(el=>el.addEventListener('click',()=>setState({[key]:el.dataset[key]})));
$('#furniture').addEventListener('change',e=>setState({furniture:e.target.checked}));$('#full-walls').addEventListener('change',e=>setState({walls:e.target.checked?'full':'low'}));$('#reset-camera').addEventListener('click',()=>{setState({view:'iso'});model?.setView('iso');});
$('#share').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Ссылка с выбранным вариантом скопирована');}catch{const input=document.createElement('textarea');input.value=location.href;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const ok=document.execCommand('copy');input.remove();toast(ok?'Ссылка с выбранным вариантом скопирована':'Скопируйте адрес страницы из адресной строки');}});
$('#save-image').addEventListener('click',async()=>{if(!model)return;try{const blob=await (await fetch(model.capture())).blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.download=`apartment-${state.variant}-${state.palette}.png`;a.href=url;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Снимок подготовлен — проверьте загрузки браузера');}catch(error){console.error('PNG export failed',error);toast('Не удалось подготовить снимок. Попробуйте другой браузер.');}});
const dialog=$('#plan-dialog');$('#open-plan').addEventListener('click',()=>dialog.showModal());$('#close-plan').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('hashchange',()=>{state=parseState(location.hash);updateUI();model?.rebuild(state);model?.setView(state.view);});
updateUI();
try{const {createApartment}=await import('./scene.js');model=createApartment($('#viewer'),room=>{$('#room-title').textContent=room.name;$('#room-description').textContent=room.info;});model.rebuild(state);model.resize();model.setView(state.view);$('#loading').remove();document.body.dataset.ready='true';}catch(error){console.error('3D initialization failed',error);$('#loading').classList.add('error');$('#loading').innerHTML='3D недоступен в этом браузере. Попробуйте включить аппаратное ускорение или открыть страницу в другом браузере. Исходный план и описание вариантов доступны ниже.';$('#save-image').disabled=true;}
