import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const el=document.querySelector('#bath-viewer');
const scene=new THREE.Scene();scene.background=new THREE.Color('#e9e6de');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;el.append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(38,1,.1,50),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(1.5,1,1.1);
scene.add(new THREE.HemisphereLight('#fffdf6','#9aa18f',2.3));const key=new THREE.DirectionalLight('#fff1d5',2.4);key.position.set(-3,7,4);scene.add(key);const root=new THREE.Group();scene.add(root);
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.75});function box(w,h,d,x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),M(c));m.position.set(x,y+h/2,z);m.castShadow=true;root.add(m);return m;}function cyl(r,h,x,y,z,c){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),M(c));m.position.set(x,y+h/2,z);root.add(m);return m;}
box(2.97,.08,2.28,1.485,0,1.14,'#d9d3c5');box(2.97,2.75,.12,1.485,0,2.22,'#d5d0c4');box(.12,2.75,2.28,2.91,0,1.14,'#d5d0c4');box(.12,2.75,1.48,0,0,.74,'#d5d0c4');box(.12,2.75,.56,0,0,2,'#d5d0c4');box(1.35,2.75,.12,.68,0,.06,'#d5d0c4');box(1,2.75,.12,2.47,0,.06,'#d5d0c4');
box(1.67,2.25,.70,1,0.04,1.52,'#b7956c');box(.85,.82,.50,.58,.04,.35,'#b7956c');box(.85,.06,.50,.58,.86,.35,'#f1f0e8');cyl(.17,.025,.58,.925,.35,'#a8bbb0');box(.74,.92,.025,.58,1.15,.08,'#aab8ae');
box(.54,.23,.52,1.33,.43,.37,'#eeeee7');box(.54,1.05,.18,1.33,.10,.63,'#c5c2b7');box(1.10,.05,1.58,2.35,.04,1.15,'#d4ddd5');box(.035,2.1,1.52,1.8,.05,1.15,'#bfcfc5');box(.80,.42,.45,.42,.02,-.42,'#b7956c');
const lights=[];for(const [x,z] of [[.55,.75],[1.45,.75],[2.35,.75],[1.45,1.75]])lights.push(cyl(.07,.03,x,2.66,z,'#f6e6b4'));lights.push(box(.035,.75,.035,.1,1.1,.35,'#e9d49a'));const night=box(1,.025,.025,1,.1,.08,'#e5bf75');
function frame(k='iso'){if(k==='top'){camera.position.set(1.5,7,1.2)}else if(k==='door'){camera.position.set(-4.5,2.9,-3.4)}else camera.position.set(4.8,3.4,4.6);controls.update()}frame();function resize(){const r=el.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();(function loop(){requestAnimationFrame(loop);renderer.render(scene,camera)})();document.querySelector('#loading')?.remove();
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-camera]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');frame(b.dataset.camera)});document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-light]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');const n=b.dataset.light==='night';lights.forEach(x=>x.visible=!n);night.visible=n;key.intensity=n?.2:2.4});
const data={layout:['01 / РАССТАНОВКА','Ваша схема, собранная в план','Шкаф 1670×700 мм · умывальник 850×500 мм · душ 1100×1577 мм · дверь 800 мм'],light:['02 / СВЕТ','Четыре режима вместо одной люстры','Потолок 3000 K, подсветка зеркала, отдельная точка душа и ночная линия под тумбой.'],power:['03 / РОЗЕТКИ','Точки, которые стоит заложить заранее','R1: две точки у тумбы · R2: зеркало · R3: резерв в шкафу · вентилятор к существующему каналу.']};
function plan(k){const d=data[k];document.querySelector('#layer-kicker').textContent=d[0];document.querySelector('#layer-title').textContent=d[1];document.querySelector('#layer-content').innerHTML='<p class="plan-copy">'+d[2]+'</p><p class="note">Высоты и зоны предварительные; трассы кабелей и монтаж уточняются по обмерам.</p>';document.querySelector('#plan').innerHTML='<svg viewBox="0 0 100 100"><rect x="7" y="7" width="86" height="86" fill="#f8f6ef" stroke="#667261"/><rect x="58" y="20" width="31" height="31" fill="#dce6df"/><rect x="18" y="68" width="18" height="12" fill="#b7956c"/><rect x="40" y="68" width="18" height="12" fill="#eee"/><rect x="18" y="11" width="48" height="10" fill="#b7956c"/><text x="50" y="97" text-anchor="middle" font-size="4">2970 × 2280 мм</text></svg>'}plan('layout');document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-layer]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');plan(b.dataset.layer)});document.querySelector('#snapshot').onclick=()=>{const a=document.createElement('a');a.download='bathroom-concept.png';a.href=renderer.domElement.toDataURL();a.click()};document.querySelector('#print').onclick=()=>print();document.querySelector('#share').onclick=async()=>{await navigator.clipboard?.writeText(location.href);const s=document.querySelector('#status');s.textContent='Ссылка скопирована';s.classList.add('show');setTimeout(()=>s.classList.remove('show'),1500)};
