import {readState,writeState,designs,views} from './bathroom-data.js?v=3';
import {drawing,sheets} from './bathroom-drawings.js?v=3';
let state=readState(location.hash),model,lastDesign;
const $=s=>document.querySelector(s);
const imagePath=(design,view)=>`assets/bath-r3-${design}-${view}.webp`;
const details=[['storage','Шкаф вровень с шахтой','503 мм — общая глубина. Фасады заканчиваются на одной линии с лицом шахты.'],['niche','Полки справа от шахты','Пять полок в нише 354 мм и вертикальная подсветка. Шахта остаётся целой.'],['shower','Душ на правой стене','Смеситель, ручная и верхняя лейки; прозрачный экран и линейный слив.'],['vanity','Умывальник и зеркало','Подвесная тумба 850 мм, два ящика, круглая подсветка и свет под мебелью.']];
const captions={iso:'Общий вид: ближние стены и зеркало скрыты для обзора',door:'Вид от двери: душ на правой стене по исходному плану',storage:'Фасад шкафа и шахта в одной плоскости; полки справа',niche:'Ниша 354 × 503 мм справа от шахты · пять полок',shower:'Душевая система на правой стене · ниша слева в этом ракурсе',vanity:'Тумба 850 × 500 мм · зеркало Ø 800 мм',top:'Вид сверху ориентирован как исходная схема'};
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600);}
$('#design-options').innerHTML=Object.entries(designs).map(([key,p])=>`<button class="design-card" data-design="${key}" aria-pressed="${state.design===key}"><img src="${imagePath(key,'shower')}" alt="${p.name}: душевая и полки" loading="lazy"><span class="design-card-copy"><small>${p.tag}</small><b>${p.name}</b><span class="mini-palette">${[p.wall,p.wood,p.shower==='tile'?p.accent:p.cabinet,p.metal].map(c=>`<i style="background:${c}"></i>`).join('')}</span><span class="choice-label">Посмотреть дизайн ↗</span></span></button>`).join('');
$('#view-controls').innerHTML=Object.entries(views).map(([key,label])=>`<button data-view="${key}" aria-pressed="${state.view===key}">${label}</button>`).join('');
$('#detail-gallery').innerHTML=details.map(([view,title,description])=>`<article><button data-detail="${view}" aria-label="${title}: открыть в 3D"><img data-render="${view}" src="${imagePath(state.design,view)}" alt="${title}" loading="lazy"><span>Открыть в 3D ↗</span></button><h3>${title}</h3><p>${description}</p></article>`).join('');
function renderDesign(){if(lastDesign===state.design)return;lastDesign=state.design;const p=designs[state.design];$('#design-tag').textContent=p.tag;$('#design-name').textContent=p.name;$('#design-description').textContent=p.description;$('#design-tradeoff').textContent=p.tradeoff;$('#hero-render').src=imagePath(state.design,'storage');$('#hero-caption').textContent=p.tag+' / '+p.name;$('#material-heading').textContent=p.name;document.querySelectorAll('[data-render]').forEach(img=>img.src=imagePath(state.design,img.dataset.render));
 const colors=[p.wall,p.wood,p.shower==='tile'?p.accent:p.cabinet,p.metal];$('#material-grid').innerHTML=p.materials.map((label,i)=>`<article><div class="swatch ${i===0?p.surface:i===1?'timber':''}" style="--swatch:${colors[i]};background-color:${colors[i]}"><span>М0${i+1}</span></div><h3>${label}</h3><p>${['Основные стены и пол. Матовый керамогранит; рисунок выбираем по образцу.','Тон древесины. В мокрой зоне — керамогранит под дерево.','Акцент выбранного дизайна. Цвет согласуем с основным камнем.','Смесители, душевая система и тонкие профили стекла.'][i]}</p></article>`).join('');}
function renderSheet(){const s=sheets[state.sheet];$('#sheet-title').textContent=s.title;$('#sheet-subtitle').textContent=s.subtitle;$('#sheet-number').textContent='ЛИСТ '+s.number;$('#drawing').innerHTML=drawing(state.sheet,state.design);$('#sheet-note').textContent=s.note;$('#sheet-items').innerHTML=s.items.map(([a,b])=>`<article><h3>${a}</h3><p>${b}</p></article>`).join('');}
function update(){for(const key of ['view','light','sheet','design'])document.querySelectorAll(`[data-${key}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[key]===state[key])));renderDesign();renderSheet();$('#view-caption').textContent=captions[state.view];if(model){model.design(state.design);if(model.activeView!==state.view)model.view(state.view);model.lighting(state.light);}}
for(const key of ['view','light','sheet','design'])document.querySelectorAll(`[data-${key}]`).forEach(b=>b.addEventListener('click',()=>{state[key]=b.dataset[key];history.replaceState(null,'',writeState(state));update();}));
document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.detail;history.replaceState(null,'',writeState(state));update();$('#model').scrollIntoView({behavior:'smooth'});}));
addEventListener('hashchange',()=>{if(location.hash.includes('=')){state=readState(location.hash);update();}});
$('#share').addEventListener('click',async()=>{try{const url=new URL(location.href);url.hash=writeState(state);await navigator.clipboard.writeText(url.href);notify('Ссылка на выбранный дизайн и ракурс скопирована');}catch{notify('Не удалось скопировать. Скопируйте адрес из строки браузера.');}});
$('#snapshot').addEventListener('click',()=>{if(!model)return notify('Модель ещё не загружена');const a=document.createElement('a');a.download=`sanuzel-${state.design}-${state.view}-${state.light}.png`;a.href=model.capture();a.click();});
$('#print').addEventListener('click',()=>window.print());update();
try{const {createBathroom}=await import('./bathroom-scene.js?v=3');model=createBathroom($('#bath-viewer'));$('#loading')?.remove();update();}catch(error){console.error('Bathroom 3D:',error);$('#loading').textContent='3D недоступно в этом браузере. Крупные виды и размерные схемы ниже работают.';}
